// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzn3QR7xkIoNvJWeHFjEMhFDkeuz_zHgw',
    appId: '1:24931602437:web:8d1c0fbac854e767f24c6c',
    messagingSenderId: '24931602437',
    projectId: 'ekikrit-eb714',
    authDomain: 'ekikrit-eb714.firebaseapp.com',
    storageBucket: 'ekikrit-eb714.firebasestorage.app',
    measurementId: 'G-J5N4XY4K8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJlSozr-d9ExZ8sKaPDA6gEqYictUKr_k',
    appId: '1:24931602437:android:1419996afdb46524f24c6c',
    messagingSenderId: '24931602437',
    projectId: 'ekikrit-eb714',
    storageBucket: 'ekikrit-eb714.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYvAYM3kvMqtCRwegmNa-_DYTrbXsEnfs',
    appId: '1:24931602437:ios:aeb9c5b991d77b2ef24c6c',
    messagingSenderId: '24931602437',
    projectId: 'ekikrit-eb714',
    storageBucket: 'ekikrit-eb714.firebasestorage.app',
    iosBundleId: 'com.example.ekikrithHackthon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYvAYM3kvMqtCRwegmNa-_DYTrbXsEnfs',
    appId: '1:24931602437:ios:aeb9c5b991d77b2ef24c6c',
    messagingSenderId: '24931602437',
    projectId: 'ekikrit-eb714',
    storageBucket: 'ekikrit-eb714.firebasestorage.app',
    iosBundleId: 'com.example.ekikrithHackthon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzn3QR7xkIoNvJWeHFjEMhFDkeuz_zHgw',
    appId: '1:24931602437:web:bd88e20cd375662ef24c6c',
    messagingSenderId: '24931602437',
    projectId: 'ekikrit-eb714',
    authDomain: 'ekikrit-eb714.firebaseapp.com',
    storageBucket: 'ekikrit-eb714.firebasestorage.app',
    measurementId: 'G-HSQ5G4THVL',
  );
}
